title: 'esohinformatics: smart bioinformatics'
author: 
  name: Kevin Esoh
  email: esohkev@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  
show_excerpts: false # set to true to show excerpts on the homepage
show_drafts: true
show_downloads: false
google_analytics: true

#domain: esohinformatics
#url: "https://esohinformatics.com" # the base hostname & protocol for your site, e.g. http://example.com

github:
  owner_url: https://github.com/esohkevin
  owner_name: kesoh
  repository_url: https://github.com/esohkevin/esohkevin.github.io
  repository_name: esohinformatics
  is_project_page: true
  baseurl: https://esohinformatics.com

buttons:
  zip_title: View on GitHub
  github_hide: false

pages:
  baseurl: https://esohkevin.github.io
  home: /index.html
  about: /about.html
  contact: /contact.html


# point to my logo
logourl: /assets/img/esohinfo2.png
logoalt: esohlogo

# title: Cayman theme
# description: Cayman is a clean, responsive theme for GitHub Pages.
# show_downloads: true
# google_analytics:
# theme: jekyll-theme-cayman

