title: esohinformatics
author: 
  name: Kevin Esoh
  email: esohkev@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  esohinformatics

remote_theme: just-the-docs/just-the-docs